### ISSUE TITLE
Text layer

### ISSUE THREAD

**Issue by artemnovichkov** [zeplin/zeplin-extension-documentation#10]
Zeplin version:
1.25.1
I'm going to add code snippets for attributed strings. I added a test function for a layer:
```js
export function layer(context, layerParams) {
  let string = '';

  string = layer.name;

  let result = {};
  if (string.length) {
    result = {
      code: string,
      mode: 'swift',
    };
  }
  return result;
}
```
But it won't work for text layer.

**Comment by berkcebi** [comment]
This could be related to `layerParams`, looks like you referenced to it as `layer` below. If you use the Console app and search for your extension name, you should be able to see the exceptions being logged there.

**Comment by berkcebi** [comment]
Closing this one, let me know if you're still running into issues @artemnovichkov!

Will ping you soon about the publishing process.
