### ISSUE TITLE
Rect corner radius

### ISSUE THREAD

**Issue by ignatovSA** [zeplin/zeplin-extension-documentation#11]
It would be great to have the possibility to get rect's corner radius, if present.

https://github.com/zeplin/zeplin-extension-documentation/blob/master/model/layer.md#layerrect--object

![image](https://user-images.githubusercontent.com/8275916/36933306-68f59860-1f09-11e8-9cdc-8e6016d228b3.png)

**Comment by merih** [comment]
You can get the radius as the [borderRadius](https://github.com/zeplin/zeplin-extension-documentation/blob/master/model/layer.md#layerborderradius--number) property from layer object. Right now it's available when all of the radii have the same value, we may add support for multiple different radius values in the future.
