### ISSUE TITLE
Any ETA on the example extensions mentioned in the README?

### ISSUE THREAD

**Issue by linakis** [zeplin/zeplin-extension-documentation#12]
I have started playing around with the API in https://github.com/linakis/zeplin-extension-spannablestring/ to create an Android equivalent for NSAttriburedString and I would ❤️ some ideas

**Comment by berkcebi** [comment]
That's awesome! ❤️ We've just open sourced our [React Native extension](https://github.com/zeplin/react-native-extension), attributed strings will hopefully follow. We're also about to launch an extension manager, a CLI tool to quickly create and test extensions—check back at the React Native extension repo in a few days to see it in action.

Mind pinging us at extensions@zeplin.io as well? We can start working together to publish your extension to everyone!
