### ISSUE TITLE
layer.textStyles have no ranges

### ISSUE THREAD

**Issue by artemnovichkov** [zeplin/zeplin-extension-documentation#16]
## Zeplin version
1.25.1 (382)
## Extension code
```js
function layer(context, layerParams) {
  let string = '';
  layerParams.textStyles.forEach(object => {
    string += `${object.style}`;
    string += `${object.range.location}`;
    string += `${object.range.length}`;
    string += `\n`;
  });

  let result = {};
  if (string.length) {
    result = {
      code: string,
      mode: 'swift',
    };
  }
  return result;
}
```
## Generated snippet:
![screen shot 2018-03-12 at 22 42 37](https://user-images.githubusercontent.com/5051597/37296986-bb823e82-2646-11e8-90f8-fef9d881371c.png)

--

Why there are no ranges and styles?

**Comment by berkcebi** [comment]
Sorry about that @artemnovichkov, looks like the docs were out of date—just pushed the change.
`result` object should have a `start` and `end` property and the style property should be named `textStyle`: https://github.com/zeplin/zeplin-extension-documentation/commit/13d5f7acd43c9086c4d201f79910fdac32211f2b

Thanks for the report!
