### ISSUE TITLE
Generate React Native components tree (as in RN's render() method)

### ISSUE THREAD

**Issue by irodin87** [zeplin/zeplin-extension-documentation#18]
Is this functionality on the to-do list? 
I found no way to determine whether components (layers) are nested inside each other or not.
Of course, there is rect object in layer, but comparing rects' coordinates is not great way of checking nesting (it is not deterministic).

**Comment by berkcebi** [comment]
Now that Zeplin projects have a list of components, the plan is to expose the component data along with it's layer hierarchy—will post updates under issue #30.

Here's more information on the new components feature: https://blog.zeplin.io/introducing-zeplin-2-0-components-and-a-ton-more-goodies-7c09dacc1f48
