### ISSUE TITLE
Async functions no response

### ISSUE THREAD

**Issue by isaozler** [zeplin/zeplin-extension-documentation#20]
is there any support for async responses? or planned?

`npm run exec -- layer`

executes the method and when resolved the response gets printed on the terminal / console

but when I select a layer in Zeplin the promise method never gets triggered...

**Comment by berkcebi** [comment]
Thanks @isaozler, wanted to let you know that we've started working on this!

**Comment by isaozler** [comment]
Great!

**Comment by berkcebi** [comment]
Hey @isaozler, sorry for the delay on this. You should now be able to return a promise from an extension function and Zeplin 2.0 should invoke the promise!

**Comment by isaozler** [comment]
hey @berkcebi
![image](https://user-images.githubusercontent.com/1378630/42094608-fd57e56a-7bb8-11e8-9d59-586c04684112.png)
![image](https://user-images.githubusercontent.com/1378630/42094631-0ff1c2c2-7bb9-11e8-9ec5-3313812145a5.png)

when I delay the response with setTimeout I get no response?
