### ISSUE TITLE
Mode or language?

### ISSUE THREAD

**Issue by artemnovichkov** [zeplin/zeplin-extension-documentation#22]
According to docs, there is `mode` property in [CodeExportObject](https://github.com/zeplin/zeplin-extension-documentation/blob/master/model/extension.md#CodeExportObject) but you use `language` property in [react-native-extension example](https://github.com/zeplin/react-native-extension/blob/ad8ef2940c528a46dd6091811fa344bd3cbd401f/src/index.js#L13-L16). 
  What should I use? Is it related to this [saving issue](https://github.com/artemnovichkov/zepcode/issues/16)?

**Comment by dirtybit** [comment]
@artemnovichkov Sorry for the confusion! The name of that property was `mode` initially but we thought that `language` is semantically better. Actually, both of them are supported but you can consider `mode` as deprecated. Use `language` to be on the safe side. 

I just updated the docs. Thanks for reporting this!
