### ISSUE TITLE
Expose screen data

### ISSUE THREAD

**Issue by isaozler** [zeplin/zeplin-extension-documentation#25]
Is there a way to retrieve screen info like screen section, name, tags

**Comment by morrislaptop** [comment]
And size!

**Comment by goldnarms** [comment]
And a list of layers.

**Comment by holmesadrianh** [comment]
@goldnarms, perhaps you want something similar to my reuest/issue: #27 

The idea is to be able to toggle a layers visibility, and ideally list the layers. I really need this as a developer trying to make the build process a bit more efficient. Are you looking for something similar? Maybe you can support my issue to see if we can get a response?

Let me know your thoughts.

**Comment by berkcebi** [comment]
Hey hey, sorry for the delay here. This is definitely on our to-do list! The plan is to expose the screen data (name, tags, size and so on) along with its layers—pretty excited about the things that can be accomplished with this data.

We'll be running tests with larger screens, to make sure that we're not running into performance issues. Will keep this issue up-to-date!
