### ISSUE TITLE
How can we have Settings?

### ISSUE THREAD

**Issue by morrislaptop** [zeplin/zeplin-extension-documentation#26]
Like in the Zeplin HTML and CSS extensions

**Comment by berkcebi** [comment]
Hey hey!

Sure, it's possible to define options in your `package.json` file: https://github.com/zeplin/zeplin-extension-documentation/blob/master/package.md#options--arrayoption …and here's an example: https://github.com/zeplin/react-native-extension/blob/develop/package.json#L31

Then in your code, you can query the option via `context.getOption`: https://github.com/zeplin/zeplin-extension-documentation/blob/master/model/context.md#contextgetoptionid--number—boolean—string

Hope this helps!
