### ISSUE TITLE
Methods/functions to change layer visibility (show/hide layers) or list layers in a panel

### ISSUE THREAD

**Issue by holmesadrianh** [zeplin/zeplin-extension-documentation#27]
Hi there,

As a developer using Zeplin, the only drawback I have come across is not being able to toggle layers. In almost all other tools I have used I am able to hide/show layers. This allowed the designer to contain multiple elements and components such as dropdowns and modals, along with various states, in a single design. This also allows me to easily toggle these layers. To be honest, this is quite an important feature to develop more rapidly and it would simplify things for the design. Since this feature is not default or available in any extension that I am aware of, I would like to find out (before I start) if the extension api gives me any control to hide layers within Zeplin? Potentially even list layers.

2 Scenarios:

Options 1 (The simplest approach):
When selecting an item in Zeplin, a button to show/hide the layer becomes available. However, not sure how I would show a hidden item if I cannot click it once its hidden.

Option 2 (Ideal scenario):
A layers panel where you can see all layers along with their grouping to be able to quickly navigate and toggle layer visibility.

I am willing to develop the extension myself, however, I need to confirm I am even the control I need with the existing api?

Any feedback is much appreciated and thanks for the help!

**Comment by berkcebi** [comment]
Hello @holmesadrianh!

Toggling layer visibility would be pretty useful like you mentioned but this is sadly not in the scope of what extensions can do. As layers are not rendered in real time in Zeplin, it's not possible to toggle their visibility on the go.

Displaying a layer list would be possible after exposing the screen data (#25) but I'm afraid it would not be interact-able as the current extension infrastructure is designed to display code snippets only. We are brainstorming on alternatives where extensions could display a proper UI though, will keep everyone posted on that.

Closing this issue for now, we'll be posting updates on exposing the screen data on issue #25. Sorry for not being able to provide a proper solution at this moment. 😢
