### ISSUE TITLE
Unable to show Styleguide Text Styles

### ISSUE THREAD

**Issue by skywall** [zeplin/zeplin-extension-documentation#28]
Hello guys,

I have following extension:
```
function layer(context, selectedLayer) {
  return {
    code: JSON.stringify({ hello: 1 }),
    language: "json"
  };
}

function styleguideTextStyles(context, textStyles) {
  return {
    code: JSON.stringify({ hello: 1 }),
    language: "json"
  };
}

export default {
  layer,
  styleguideTextStyles
};
```

Just some random JSON values. `layer` works as expected, code snippet in Zeplin is visible. The problem is `styleguideTextStyles` does not show up. I have tried running my function separately via: `npm run exec -- styleguideTextStyles` and it works fine.

Maybe there are some Zeplin **v2.0** related changes, what are not described in documentation?

Thanks.

**Comment by berkcebi** [comment]
Might be related to 2.0 indeed, thanks a lot for the report @skywall—looking into it.

For now, defining the `comment`/`styleguideColors` functions and returning dummy values might fix the issue. Will post updates here!

**Comment by berkcebi** [comment]
Just fixed the issue @skywall, next macOS app release will contain the fix!

**Comment by berkcebi** [comment]
2.0.2 is out and should contain the fix—thanks again for the report @skywall!
