### ISSUE TITLE
URL for local (private) extensions doesnt work with Windows / Web app

### ISSUE THREAD

**Issue by mahish** [zeplin/zeplin-extension-documentation#29]
`https://internal.domain.com/node_modules/@some-package/zeplin-extension/dist/manifest.json`

URL works fine in Mac app but doesnt work in Web / Windows app. Tried both `@` and `%40` in the URL.

Mac Zeplin version: 2.0.1
<img width="396" alt="image" src="https://user-images.githubusercontent.com/3687943/41913570-f2cc5f78-7950-11e8-866d-965f11ceb684.png">

Windows Zeplin version:
![image](https://user-images.githubusercontent.com/3687943/41913599-05eb8c32-7951-11e8-9d81-6f477fde1cbc.png)

Web version:
???

This issue blocks using Zeplin in my company. Any idea? Thanks!

**Comment by berkcebi** [comment]
Thanks for the report @mahish, looking into this.

**Comment by dirtybit** [comment]
@mahish This might be a CORS issue since the extension files are being served through an internal domain rather than localhost. Can you make sure that the extension server is configured to respond requests with required CORS headers?

**Comment by mahish** [comment]
@dirtybit Thanks for your reply. I can and Ill let u know if I find something. However, the extension works perfectly fine on any Mac (Mac app) I tried.

**Comment by mahish** [comment]
@dirtybit I tried custom `XMLHttpRequest` to get the `manifest.json` and yes, the request was blocked because of missing CORS headers. However, we dont want to open it from everywhere. How do you access the file? Via `XMLHttpRequest` or in other way? Do you suggest something? Still dont get why Mac app works tho…

**Comment by mahish** [comment]
@dirtybit So we tried `Access-Control-Allow-Origin: *` on our server and it works everywhere now. Still confused about the Mac app tho.

**Comment by berkcebi** [comment]
Glad to hear that @mahish!

Mac app does not require CORS headers to be set up to download the plugin sources, as it's not running behind a browser. We should try and display a proper error in this case on the Web app as well—thanks a lot for reporting this.

**Comment by merih** [comment]
You can also limit the origins that have access to your servers to "app.zeplin.io" rather than wildcard, to limit the exposure of your internal servers.
