### ISSUE TITLE
Make documentation more clear about how to enable local extensions.

### ISSUE THREAD

**Issue by wgrabowski** [zeplin/zeplin-extension-documentation#32]
I'm very happy that local extension can be tested on Web and Windows apps now, however it took me some time to figure out what "Option key" is in this sentence from tutorial:

> On Mac, Windows or Web apps, holding down the Option key will enable the “Add Local Extension” option on the title bar

I'm not neither Mac user nor English native speaker so I was confused until I've google that Option is Alt 
key in my keyboard.  

I suggest that you specify that Alt or Options key should be used to avoid such confusion for people not familiar with Mac keyboard.

**Comment by berkcebi** [comment]
Hey @wgrabowski, that definitely makes sense.

Would you like to fix that and open a PR?
