### ISSUE TITLE
Adobe Xd to zeplin unable to export

### ISSUE THREAD

**Issue by judealbania** [zeplin/zeplin-extension-documentation#33]
![image](https://user-images.githubusercontent.com/17874571/44375338-c0186f80-a525-11e8-8547-fa318d6f8cf8.png)

 zeplin and adobe xd are up to date.

**Comment by berkcebi** [comment]
Sorry to hear that @judealbania. This repo is only for issues related to [Zeplin extensions](https://extensions.zeplin.io) though, would you mind sending the screenshot (along with the app logs) to support@zeplin.io? We'll get back to you as soon as possible!
