### ISSUE TITLE
layer.textStyles have no names

### ISSUE THREAD

**Issue by mrrhysbutler** [zeplin/zeplin-extension-documentation#43]
When accessing textStyles via the `selectedLayer` object, they do not appear to have a corresponding name (but all other info appears correctly). However, when querying `styleguideTextStyles`, all names are correctly returned.

In the Zeplin Mac app, the style name is correctly displayed in the info panel.

Currently running macOS app Version 2.2.5 (609). Any ideas? Thanks.

**Comment by dirtybit** [comment]
Currently, text style objects on the selected do not have their name field populated from the project's styleguide. You need to look it up in the project to see if there's a matching text style. You can use [`Project.findTextStyleEqual`](https://github.com/zeplin/zeplin-extension-documentation/blob/master/model/project.md#projectfindtextstyleequaltextstyle--textstyle) method for this. 

The behavior is also same for colors in layers:
https://github.com/zeplin/zeplin-extension-documentation/issues/7

**Comment by mrrhysbutler** [comment]
Thanks for the clarification
