### ISSUE TITLE
Source Library of Master Symbol?

### ISSUE THREAD

**Issue by chris-dura** [zeplin/zeplin-extension-documentation#46]
Quite often in our Sketch files we may be using several External Libraries. Those libraries can have Master Symbols named the same thing, eg. "Button/Primary/Default".

The [master-symbol-name](https://extensions.zeplin.io/javinor/zeplin-master-symbol-name-extension) extension does a great job of giving the "master symbol name" for the components; however, it can be confusing if the symbols are from different libraries, but have the same name.

Is there any way to get access to what Library the Symbol actually belongs to??

**Comment by dirtybit** [comment]
Hey @chris-dura 

This data is not stored in Zeplin for now. I'll let you know if that changes down the line!

**Comment by chris-dura** [comment]
Hey @dirtybit -- One of my designers mentioned in passing that Zeplin may have shipped some updates that may let them see the "source library" where a symbol is "coming from"?

I haven't had a chance to dig in yet, but just thought I'd comment here ahead of time on the off chance you could confirm if that data (if it exists) is accessible to extensions?
