### ISSUE TITLE
ERROR: Fetching extension manifest failed, view logs for details.

### ISSUE THREAD

**Issue by chris-dura** [zeplin/zeplin-extension-documentation#47]
I'm building a local extension, which I have deployed to an internal server (see #44), so that other team members can use it, e.g. http://my-zeplin-ext.mycompany.com/manifest.json

I have no problem installing it on my Zeplin Mac App.
However, other team members get the following error:
```
Fetching extension manifest failed, view logs for details.
```
Where/how can I view these "logs"?

**Comment by dirtybit** [comment]
Hey @chris-dura 

You can follow these steps to view logs from the macOS app:
https://github.com/zeplin/zeplin-extension-documentation/issues/40#issuecomment-488483664

We'll add these steps to the docs as well.
