### ISSUE TITLE
Info about supported JS features in extension

### ISSUE THREAD

**Issue by pabaibara** [zeplin/zeplin-extension-documentation#8]
I'm sorry but I didn't find any references to descriptions of which ECMAScript standards supported by Zeplin extensions. 

After having few experiments by indirect signs, I was able to find out:
- features from ES2016 are working;
- modules (neither CommonJS and not JavaScript standard modules) doesn't work;

Am I right? It will be cool if you provide a little bit of information about supported ECMAScript features.

**Comment by berkcebi** [comment]
Yes, that's something we're definitely missing. Currently extensions on the Mac app run on JavaScriptCore, and we support El Capitan and up. We do have an internal list of features that we follow, will update the docs accordingly.

**Comment by pabaibara** [comment]
Okay, thank's a lot.
