### ISSUE TITLE
Request for adding link to Zeplin extention boilerplate with webpack

### ISSUE THREAD

**Issue by pabaibara** [zeplin/zeplin-extension-documentation#9]
My friend and I spent a little time and build a small extension project boilerplate based on webpack ([Zero](https://github.com/baybara-pavel/zero)) to save a time for the community.
We will be very glad if you can place a link to our project in the documentation. In any case, we will be happy to hear any your feedback.
Thank you.

**Comment by berkcebi** [comment]
Hey @baybara-pavel, that's amazing—thanks a lot for the effort!

We're also working on a similar extension boilerplate package actually, with a few more features like publishing and testing. I'll make sure to add the link to Zero in the documentation.

**Comment by pabaibara** [comment]
Cool, thanks! Features like testing will be really helpful and that's we really need, because right now debugging process seems too much hard 😞

**Comment by berkcebi** [comment]
Hey @baybara-pavel, we just released [zem](https://github.com/zeplin/zem)—Zero is mentioned there as well, as an alternative solution. Hope you'll like it!

**Comment by pabaibara** [comment]
@berkcebi, ZEM looks amazing! Next our ext. we will build with official solution.
Thank's a lot for link to Zero project) Right now, I'll add a back-link to ZEM - you made a really cool thing!
